# This workflow is triggered when publishing a GitHub release
on: push
    
jobs:
  test_me:
    runs-on: ubuntu-latest
    steps:
      - name: Run analysis
        uses: wouter-admiraal-sonarsource/sonarqube-scan-action@master
